stages:
  - build
  - tests

compilar:
  stage: build
  image: maven:3.8-openjdk-17
  cache:
    paths:
      - .maven
    key:
      files:
        - back-end/pom.xml
  script:
    - ./back-end/build.sh

probar:
  stage: tests
  image: maven:3.8-openjdk-17
  cache:
    paths:
      - .maven
    key:
      files:
        - back-end/pom.xml
  script:
    - ./back-end/run-tests.sh
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
